### ISSUE TITLE
Access for terraform_ngic_deployment.git 

### ISSUE THREAD

**Issue by manianps** [omec-project/deployment#2]
Hi, Where can we access the terraform_ngic_deployment for opensource? In the /omec-project/deployment it is mentioned as below:
Make sure network access to "ilpm.intel-research.net" server is available.
Make sure user account for package repository is created.
Download the package using following commands:
>cd /opt/
>git clone https://<username>@ilpm.intel-research.net/bitbucket/scm/vccbbw/terraform_ngic_deployment.git
But for open source community, we don't have access. Please suggest.

**Comment by mgunjan** [comment]
i Believe the readme is not update to date. It is referencing to older location where this project was being hosted before it was open sourced. you should be cloning this project itself for deployment code.
git clone https://github.com/omec-project/deployment.git

**Comment by manianps** [comment]
thanks for the clarification.

**Comment by manianps** [comment]
Will check the latest README change.
