### ISSUE TITLE
Unable to locate script generate_device.sh 

### ISSUE THREAD

**Issue by manianps** [omec-project/deployment#3]
>cd /opt/terraform_ngic_deployment/terraform
 >./generate_device.sh cp

In the above steps, we are unable to locate generate_device.sh script, under /opt/deployment/terraform in our local installation - anywhere under the deployment project

Please help.

**Comment by manianps** [comment]
Team, any inputs on this query?

**Comment by krsna1729** [comment]
@manianps there is a PR #5 in flight https://github.com/omec-project/deployment/blob/f3f405a10aff3c36ec8f400ac6e390af544d68bd/README.txt

Please see if that helps

**Comment by Ailnard** [comment]
> 
> 
> @manianps there is a PR #5 in flight https://github.com/omec-project/deployment/blob/f3f405a10aff3c36ec8f400ac6e390af544d68bd/README.txt
> 
> Please see if that helps

The PR does not really cover the issue IMO.
any other hints?

**Comment by krsna1729** [comment]
@amitinfo2k @wanare-2017

**Comment by amitinfo2k** [comment]
@Ailnard  generate_device.sh script is no longer in use. it's been replaced by scripts under ../terraform/scripts/network_*.sh. we will update the documentation. point I want to make is  user doesn't need to explicitly invoke this script. it will be done as part of automated deploy.

**Comment by amitinfo2k** [comment]
Readme updated, addressed by the following PR.
https://github.com/omec-project/deployment/pull/11
