### ISSUE TITLE
Minimal hardware, OS, processor, NIC requirements for a minimal LAB setup

### ISSUE THREAD

**Issue by manianps** [omec-project/deployment#4]
Can you please point us to the documentation on the minimal requirements from a LAB purpose (RnD) in our organization?

**Comment by amitinfo2k** [comment]
@manianps  Refer ReadMe.txt section #Ready the physical hardware

**Comment by manianps** [comment]
I saw that for a typical deployment below are recommended.
        CORES_PER_NODE = 26                      // CPU cores per NUMA node
        CORES_TOTAL = 52                         // Total CPU cores 
        MEMORY GB = 128                          // Total RAM
        DISK GB = 500                            // Total HDD size
        NUMA_NODES= 2                            // Minimum # of NUMA nodes
        NETWORK.ONBD = "2x10GbE"                 // Onboard NIC spec.
        NETWORK.FV710 = "8x10GbE = 2x(4x10GbE)"  // Additional NIC controllers


But, for simple lab setup to test OMEC, do we need so much?
Can we run a scaled down version with minimal Cores, Memory?

**Comment by krsna1729** [comment]
@manianps i have tried to capture resource requirements as part of kubernetes manifest some of the components - 
https://github.com/omec-project/ngic-rtc/pull/54/files
https://github.com/omec-project/c3po/pull/21/files

Also for DP you can even try to use a linux interface virtual or physical with vdev af_packet option in DPDK EAL.
