### ISSUE TITLE
Split GW deployment without FPC doesn't work

### ISSUE THREAD

**Issue by amitinfo2k** [omec-project/deployment#6]
Current deployment schema needs FPC component.
It doesn't define interface between SGWC <-Sx-> SGWU, and PGWC<-Sx->PGWU

**Comment by krsna1729** [comment]
@amitinfo2k update the issue with more verbose description

**Comment by amitinfo2k** [comment]
We no longer support FPC (not open sourced under omec). So, we will need to remove that dependency.
