### ISSUE TITLE
Prerequisite.sh script failing

### ISSUE THREAD

**Issue by amitinfo2k** [omec-project/deployment#8]
Prerequisite.sh script failing

```sh
$:/opt/deployment/setupremote# ./prerequisite.sh
**************Prerequsite Test***********************
Ansible
-------------------
./prerequisite.sh: line 11: syntax error: unexpected end of file
```

**Comment by wanare-2017** [comment]
@amitinfo2k
This issue has been resolved. 
there is a PR https://github.com/omec-project/deployment/pull/5  in flight https://github.com/omec-project/deployment/blob/a307063da57f3bfa6f1b5d413c458b12e16945e5/setupremote/prerequisite.sh
